name: Deploy Theme to Bluehost (SFTP)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 🎉 SFTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 🚀 SFTP Deploy to Bluehost Theme Folder
      uses: easingthemes/ssh-deploy@v5.1.0
      with:
        SSH_PRIVATE_KEY: ${{ secrets.BLUEHOST_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.BLUEHOST_SERVER }}
        REMOTE_USER: ${{ secrets.BLUEHOST_USERNAME }}
        ARGS: "-rlgoDIVzc --delete"
        TARGET: "/home/atrupp/public_html/wp-content/themes/austins-theme/"
